inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - '.git/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/{rails,rake,setup,update}'
    - !ruby/regexp /old_and_unused\.rb$/
    - 'Guardfile'
Rails:
  Enabled: true

# Disable Layout/IndentationConsistency: Inconsistent indentation detected.
# Allow indentation after `private` modifier keywords
Layout/IndentationConsistency:
  EnforcedStyle: rails

# Disable "Do not prefix reader method names with get_."
Naming/AccessorMethodName:
  Enabled: false

# Disable "Use nested module/class definitions instead of compact style."
Style/ClassAndModuleChildren:
  Enabled: false

# Disable "Missing top-level class documentation comment."
Style/Documentation:
  Enabled: false

# Disable "Redundant return detected."
Style/RedundantReturn:
  Enabled: false
