inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - '.git/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/{rails,rake,setup,update}'
    - !ruby/regexp /old_and_unused\.rb$/
    - 'Guardfile'
Rails:
  Enabled: true
  
# Disable "Missing top-level class documentation comment."
Style/Documentation:
  Enabled: false
